name: release-windows-x86_64

on:
  push:
    tags:
      - "v*"

jobs:
  build-windows:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            mingw-w64 \
            cmake \
            ninja-build \
            nasm \
            zip \
            jq

      - name: Install Rust toolchain
        # If you already pin via rust-toolchain.toml, this will respect it.
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-gnu

      # # Optional but recommended (aws-lc-sys builds are heavy)
      # # Not caching at this time, storage is more premium than CPU time.
      # - name: Cache cargo
      #   uses: actions/cache@v4
      #   with:
      #     path: |
      #       ~/.cargo/registry
      #       ~/.cargo/git
      #       target
      #     key: cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build (release, windows x86_64 GNU)
        env:
          # Tell aws-lc-sys we're cross-compiling
          AWS_LC_SYS_CROSS_COMPILE: "1"

          # Explicit MinGW toolchain for the Windows GNU target
          CC_x86_64_pc_windows_gnu: x86_64-w64-mingw32-gcc
          CXX_x86_64_pc_windows_gnu: x86_64-w64-mingw32-g++
          AR_x86_64_pc_windows_gnu: x86_64-w64-mingw32-ar
          RANLIB_x86_64_pc_windows_gnu: x86_64-w64-mingw32-ranlib

          # Help CMake avoid host contamination
          CMAKE_SYSTEM_NAME: Windows
          CMAKE_C_COMPILER: x86_64-w64-mingw32-gcc
          CMAKE_CXX_COMPILER: x86_64-w64-mingw32-g++
          CMAKE_AR: x86_64-w64-mingw32-ar
          PKG_CONFIG_ALLOW_CROSS: "1"
        run: |
          cargo build --release --target x86_64-pc-windows-gnu

      - name: Package artifact
        shell: bash
        run: |
          set -euo pipefail

          # Derive crate name (first package) and create a friendly archive name
          CRATE_NAME="$(cargo metadata --no-deps --format-version 1 | jq -r '.packages[0].name')"
          TAG_NAME="${GITEA_REF_NAME:-${GITHUB_REF_NAME:-unknown-tag}}"

          OUT_DIR="dist"
          mkdir -p "$OUT_DIR"

          BIN_PATH="target/x86_64-pc-windows-gnu/release/${CRATE_NAME}.exe"

          # If your produced .exe name differs (workspace, multiple bins, etc),
          # change BIN_PATH accordingly (or package the whole release dir).
          test -f "$BIN_PATH"

          ARCHIVE="${OUT_DIR}/${CRATE_NAME}-${TAG_NAME}-windows-x86_64.zip"
          zip -j "$ARCHIVE" "$BIN_PATH"

          echo "Built: $BIN_PATH"
          echo "Packaged: $ARCHIVE"

      - name: Upload artifact
        uses: https://github.com/christopherHX/gitea-upload-artifact@v4
        with:
          name: windows-x86_64
          path: dist/*.zip
          if-no-files-found: error
